import jsPDF from "jspdf";
import type { Report } from "./api";

/** Trigger a browser file download from a Blob. */
function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Build a filename stem like "AEGIS-AE-2024-047-report-2024-04-10" */
function buildFileStem(report: Report, assessmentId?: string): string {
  const id = assessmentId ?? report.report_id;
  const date = report.created_at.slice(0, 10);
  return `AEGIS-${id}-report-${date}`;
}

const SEVERITY_COLORS: Record<string, [number, number, number]> = {
  none: [16, 185, 129],
  minor: [245, 158, 11],
  moderate: [249, 115, 22],
  severe: [239, 68, 68],
  destroyed: [185, 28, 28],
};

export function downloadReportPdf(report: Report, assessmentId?: string): void {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentW = pageW - margin * 2;
  let y = margin;

  const checkPage = (needed: number) => {
    if (y + needed > pageH - margin) {
      doc.addPage();
      y = margin;
    }
  };

  // ── Title ──
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0);
  doc.text("AEGIS - Disaster Assessment Report", margin, y);
  y += 8;

  // ── Subtitle / metadata ──
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  const id = assessmentId ?? report.report_id;
  doc.text(`Assessment: ${id}`, margin, y);
  y += 5;
  doc.text(`Generated: ${new Date(report.created_at).toLocaleString()}`, margin, y);
  y += 5;
  doc.text(`Report ID: ${report.report_id}`, margin, y);
  y += 10;

  // ── Severity badge ──
  const color = SEVERITY_COLORS[report.overall_severity] ?? [100, 100, 100];
  doc.setFillColor(...color);
  doc.roundedRect(margin, y - 4, 40, 8, 2, 2, "F");
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text(report.overall_severity.toUpperCase(), margin + 20, y + 1, { align: "center" });
  doc.setTextColor(0);
  y += 14;

  // ── Horizontal rule ──
  doc.setDrawColor(200);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  // ── Summary ──
  checkPage(20);
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("Summary", margin, y);
  y += 7;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const summaryLines = doc.splitTextToSize(report.summary, contentW);
  checkPage(summaryLines.length * 5);
  doc.text(summaryLines, margin, y);
  y += summaryLines.length * 5 + 8;

  // ── Numbered section helper ──
  const addSection = (title: string, items: string[]) => {
    checkPage(20);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text(title, margin, y);
    y += 7;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    items.forEach((item, i) => {
      const lines = doc.splitTextToSize(`${i + 1}. ${item}`, contentW);
      checkPage(lines.length * 5 + 2);
      doc.text(lines, margin, y);
      y += lines.length * 5 + 3;
    });
    y += 4;
  };

  // ── Key Findings ──
  addSection("Key Findings", report.key_findings);

  // ── Recommendations ──
  addSection("Recommendations", report.recommendations);

  // ── Location ──
  if (report.location) {
    checkPage(15);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text("Location", margin, y);
    y += 7;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(
      `Coordinates: ${report.location.lat.toFixed(4)}, ${report.location.lng.toFixed(4)}`,
      margin,
      y
    );
    y += 10;
  }

  // ── Footer ──
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(`Video ID: ${report.video_id}`, margin, pageH - 10);
  doc.text("Generated by AEGIS", pageW - margin, pageH - 10, { align: "right" });

  // ── Save / download ──
  doc.save(buildFileStem(report, assessmentId) + ".pdf");
}

export function downloadReportJson(report: Report, assessmentId?: string): void {
  const json = JSON.stringify(report, null, 2);
  const blob = new Blob([json], { type: "application/json" });
  triggerDownload(blob, buildFileStem(report, assessmentId) + ".json");
}
